# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  STACK_ROOT: $(Pipeline.Workspace)/.stack
  STACK_WORK: .stack-work

jobs:
 #- job: macOS
 #  pool:
 #   vmImage: 'macOS-10.13'
 #  steps:
 #  - script:  |
 #       mkdir -p ~/.local/bin
 #       export PATH=$HOME/.local/bin:$PATH
 #       curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
 #       stack build
 - job: linux
   pool:
    vmImage: 'ubuntu-latest'
   steps:
    #- task: CacheBeta@0
    #  inputs:
    #    key: stack | $(Agent.OS)
    #    path: $(HOME)/.local/bin
    #  displayName: Cache stack
    - task: CacheBeta@0
      inputs:
        key: stack-root | $(Agent.OS) | stack.yaml
        path: $(STACK_ROOT)
      displayName: Cache stack root
    - task: CacheBeta@0
      inputs:
        key: stack-work | $(Agent.OS) | stack.yaml | version2
        path: $(Build.SourcesDirectory)/$(STACK_WORK)
      displayName: Cache stack work
    - script: |
        ghc --version
        ghc-pkg list
        pwd
        sudo apt-get update
        sudo apt-get install texlive-full texlive-binaries texlive-latex-base texlive-latex-extra texlive-math-extra texlive-lang-chinese -y
        mkdir -p ~/.local/bin
        export PATH=$HOME/.local/bin:$PATH
        curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        stack build --fast --no-system-ghc --install-ghc
        ./examples/counter.hs check
        stack path
      displayName: 'Build reanimate'
