site_name: Reanimate
repo_url: https://github.com/Lemmih/reanimate
theme:
  name: readthedocs
markdown_extensions:
  - markdown_include.include
extra_css:
  - fix.css
nav:
  - Reanimate: index.md
  - Gallery: gallery.md
  - Gluing together animations: glue_tut.md
  - Morphology: morphology.md
