site_name: Reanimate
repo_url: https://github.com/Lemmih/reanimate
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - haskell
    - plaintext
    - text
    - txt
markdown_extensions:
  - markdown_include.include
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - fix.css
nav:
  - Reanimate: index.md
  - Core concepts: introduction.md
  - Gluing together animations: glue_tut.md
  - Morphology (incomplete): morphology.md
  - Voice control: voice.md
  - How to:
    - Use fonts (incomplete): fonts.md
  - Showcase:
    - Color Theory: showcase_colortheory.md
