version: "3.8"
services:
  bot:
    image: reanimate/discord-bot
    volumes:
      - .cache:/root/.cache
    environment:
#      DISCORD_TOKEN: ''
  watch:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
