jobs:
- job: ${{ parameters.name }}
  variables:
    STACK_ROOT: $(Build.SourcesDirectory)/.stack-root
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
        STACK_YAML: stack.yaml
      stack-lts-12:
        BUILD: stack
        STACK_YAML: stack-lts-12.yaml
      stack-lts-11:
        BUILD: stack
        STACK_YAML: stack-lts-11.yaml
    maxParallel: 6
  steps:
  - task: CacheBeta@0
    inputs:
      key: ${{ parameters.name }} | "${{ parameters.vmImage }}" | $(STACK_YAML) | stack-root | $(Agent.OS) | version2
      path: $(STACK_ROOT)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache stack root
  - bash: |
        echo REMOVE ME ONCE THIS IS FIXED https://github.com/microsoft/azure-pipelines-tasks/issues/10841
        cd "$(STACK_ROOT)"
        if [ -f "executable.txt" ]; then chmod +x $(cat executable.txt); fi
    condition: and(succeeded(), ne(variables['CACHE_RESTORED'], 'false'))
  - script: |
      #brew cask install basictex
      #export PATH="/Library/TeX/texbin/:$PATH"
      #sudo tlmgr update --self
      #sudo tlmgr install standalone
      #sudo tlmgr install preview
      #sudo tlmgr install dvisvgm
      #sudo tlmgr install scheme-full
      #sudo tlmgr install amsmath
      #sudo tlmgr install physics
      #sudo tlmgr install doublestroke
      #sudo tlmgr install calligra
      #sudo tlmgr install fundus-calligra
      #sudo tlmgr install relsize
      #sudo tlmgr install wasysym
      #sudo tlmgr install cjk
      #sudo tlmgr install ctex
      #sudo tlmgr install zhnumber
      #xelatex -interaction=nonstopmode test.tex
      brew install ffmpeg
      brew install povray
      mkdir -p ~/.local/bin
      curl -skL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin;
      export PATH=$HOME/.local/bin:$PATH
      stack --install-ghc $ARGS test --only-dependencies
      stack ./examples/counter.hs check
      stack $ARGS test --pedantic
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
  - bash: |
        echo REMOVE ME ONCE THIS IS FIXED https://github.com/microsoft/azure-pipelines-tasks/issues/10841
        cd "$(STACK_ROOT)"
        rm executable.txt
        find . -perm +111 >> executable.txt
        find . -executable >> executable.txt
        cat executable.txt
    displayName: Save list of files with executable bit set
