jobs:
- job: ${{ parameters.name }}
  variables:
    STACK_ROOT: $(Build.SourcesDirectory)/.stack-root
    TEX_ROOT: $(Build.SourcesDirectory)/texlive/2019
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      # stack:
      #   BUILD: stack
      #   STACK_YAML: stack.yaml
      # stack-lts-12:
      #   BUILD: stack
      #   STACK_YAML: stack-lts-12.yaml
      stack-lts-11:
        BUILD: stack
        STACK_YAML: stack-lts-11.yaml
    maxParallel: 6
  steps:
  - task: CacheBeta@0
    inputs:
      key: ${{ parameters.name }} | ${{ parameters.vmImage }} | $(STACK_YAML) | stack-root | $(Agent.OS)
      path: $(STACK_ROOT)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache stack root
  - task: CacheBeta@0
    inputs:
      key: texlive | $(Agent.OS) | version2
      path: $(TEX_ROOT)
      cacheHitVar: TEX_CACHE_RESTORED
    displayName: Cache texlive root
  - bash: |
        echo REMOVE ME ONCE THIS IS FIXED https://github.com/microsoft/azure-pipelines-tasks/issues/10841
        cd "$(STACK_ROOT)"
        if [ -f "executable.txt" ]; then chmod +x $(cat executable.txt); fi
    condition: and(succeeded(), ne(variables['CACHE_RESTORED'], 'false'))
  - bash: |
        set -x
        envsubst < texlive.profile > tmp
        mv tmp texlive.profile
        cat texlive.profile

        curl -sSkL http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip -o install-tl.zip
        unzip install-tl.zip
        ./install-tl-*/install-tl-windows.bat -profile=texlive.profile -scheme=scheme-full
        ./texlive/2019/bin/win32/latex.exe --version
        export PATH=$PATH:"$(TEX_ROOT)"/bin/win32/
        latex.exe --version
        #tlmgr install dvisvgm
        #dvisvgm.exe --version
    condition: ne(variables['TEX_CACHE_RESTORED'], 'true')
  - bash: |
      set -x
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      #curl -sSkL https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.2.1-win64-static.zip -o ffmpeg.zip
      #unzip ffmpeg.zip
      #cp ffmpeg-4.2.1-win64-static/bin/* /usr/bin/

      export PATH=$PATH:"$(TEX_ROOT)"/bin/win32/

      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      stack --install-ghc $ARGS test --only-dependencies
      stack ./examples/counter.hs check
      stack $ARGS test --pedantic
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
  - bash: |
        echo REMOVE ME ONCE THIS IS FIXED https://github.com/microsoft/azure-pipelines-tasks/issues/10841
        cd "$(STACK_ROOT)"
        rm executable.txt
        find . -perm +111 >> executable.txt
        find . -executable >> executable.txt
        cat executable.txt
    displayName: Save list of files with executable bit set
