jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  variables:
    STACK_ROOT: $(Build.SourcesDirectory)/.stack-root
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
        STACK_YAML: stack-lts-14.yaml
        ARGS: --pedantic
    maxParallel: 6
  steps:
  - task: Cache@2
    inputs:
      key: ${{ parameters.name }} | ${{ parameters.vmImage }} | $(STACK_YAML) | stack-root | $(Agent.OS) | version 2
      path: $(STACK_ROOT)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache stack root
  - bash: |
      set -o xtrace
      #curl -sSkL https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/libblas.dll -o libblas.dll
      # curl -sSkL https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/libblas.lib -o libblas.lib
      #curl -sSkL https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.dll -o liblapack.dll
      # curl -sSkL https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.lib -o liblapack.lib
      # cp libblas.dll libblas.lib liblapack.dll liblapack.lib /usr/lib/
      # cp libblas.dll libblas.lib liblapack.dll liblapack.lib /lib/
      # cp libblas.dll libblas.lib liblapack.dll liblapack.lib /usr/local/lib/
      # cp libblas.dll libblas.lib liblapack.dll liblapack.lib /c/mingw810/prerequisites/x86_64-binutils-nomulti/x86_64-w64-mingw32/lib
      # cp libblas.dll libblas.lib liblapack.dll liblapack.lib /c/mingw810/prerequisites/x86_64-binutils-nomulti/lib
      # echo $CONDA
      # echo $PATH
      # CWD=`pwd`
      # cd "$CONDA/condabin/"
      # export PATH=`pwd`:$PATH
      # cd $CWD
      # echo $PATH
      # echo `which conda.bat`
      # echo `which conda`
      # conda info --envs
      # ls $CONDA/condabin
      # $CONDA/condabin/conda.bat create --yes --name reanimate
      # $CONDA/condabin/conda.bat activate reanimate
      # $CONDA/condabin/conda.bat
      # $CONDA/condabin/conda.bat info
      
      $CONDA/condabin/conda.bat install --yes --quiet -c conda-forge libblas liblapack
      
      # $CONDA/condabin/conda.bat install --yes --quiet -c conda-forge liblapack
      # ls "C:\Users\VssAdministrator\.conda"
      # ls "C:\Users\VssAdministrator\.conda\Library"
      # ls "C:\Users\VssAdministrator\.conda\Library\bin"
      # ls "$CONDA"
      # ls "$CONDA\Library"
      # ls "$CONDA\Library\bin"
      # find "$CONDA" -name '*libblas*'
      # find "$CONDA" -name '*lapack*'
      # export LIBRARY_PATH="`pwd`;$LIBRARY_PATH"
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/

    displayName: 'Setup'
  - bash: |
      set -o xtrace
      stack --install-ghc build $ARGS --no-keep-going --fast --only-dependencies --flag reanimate:hmatrix --flag hmatrix:openblas --extra-lib-dirs=$CONDA/Library/bin
      stack --install-ghc test $ARGS --no-keep-going --fast --flag reanimate:test --only-dependencies --flag reanimate:hmatrix --flag hmatrix:openblas --extra-lib-dirs=$CONDA/Library/bin
    displayName: 'Install dependencies'
  - bash: |
      set -o xtrace
      stack ./examples/counter.hs check
      stack test --flag reanimate:test --test-arguments="-j2" --fast --flag reanimate:hmatrix --flag hmatrix:openblas --extra-lib-dirs=$CONDA/Library/bin
    displayName: 'Build & Test'
  - bash: |
      # stack haddock --no-haddock-deps
    displayName: 'Build documentation'
