jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  variables:
    STACK_ROOT: $(Build.SourcesDirectory)/.stack-root
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      # lts-16 and lts-15 fails due to segfaults. Think it is a GHC issue.
      # stack:
        # BUILD: stack
        # STACK_YAML: stack.yaml
        # ARGS: --pedantic
      # stack-lts-15:
        # BUILD: stack
        # STACK_YAML: stack-lts-15.yaml
      stack-lts-14:
        BUILD: stack
        STACK_YAML: stack-lts-14.yaml
      stack-lts-13:
        BUILD: stack
        STACK_YAML: stack-lts-13.yaml
      stack-lts-12:
        BUILD: stack
        STACK_YAML: stack-lts-12.yaml
    maxParallel: 6
  steps:
  - task: Cache@2
    inputs:
      key: ${{ parameters.name }} | ${{ parameters.vmImage }} | $(STACK_YAML) | stack-root | $(Agent.OS) | version3
      path: $(STACK_ROOT)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache stack root
  - bash: |
      set -o xtrace
      # $CONDA/condabin/conda.bat install --yes --quiet -c msys2 m2w64-gcc-libgfortran m2w64-openblas

      # cp $CONDA/Library/mingw-w64/bin/libgfortran-3.dll $CONDA/Library/mingw-w64/bin/libgfortran.dll

      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/

    displayName: 'Setup'
  - bash: |
      set -o xtrace
      #stack --install-ghc build $ARGS --no-keep-going --fast --only-dependencies --flag reanimate:enable-hmatrix --flag hmatrix:openblas --extra-lib-dirs=$CONDA/Library/mingw-w64/bin
      stack --install-ghc build $ARGS --no-keep-going --fast --only-dependencies
      #stack --install-ghc test $ARGS --no-keep-going --fast --flag reanimate:test --only-dependencies --flag reanimate:enable-hmatrix --flag hmatrix:openblas --extra-lib-dirs=$CONDA/Library/mingw-w64/bin
      stack --install-ghc test $ARGS --no-keep-going --fast --flag reanimate:test --only-dependencies
    displayName: 'Install dependencies'
  - bash: |
      set -o xtrace
      # stack ./examples/counter.hs check
      # stack test --flag reanimate:test --test-arguments="-j2" --fast --flag reanimate:enable-hmatrix --flag hmatrix:openblas --extra-lib-dirs=$CONDA/Library/mingw-w64/bin
      stack test --flag reanimate:test --test-arguments="-j2" --fast
    displayName: 'Build & Test'
  - bash: |
      # stack haddock --no-haddock-deps
    displayName: 'Build documentation'
