name: Site checker

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ master, feature-ci ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install w3c-linkchecker node-ws
    - name: Check websocket connection
      run: |
        #/usr/local/bin/wscat --version
        #sudo npm install -g wscat
        wscat --version
        wscat --connect --help "wss://reanimate.clozecards.com:443/ws/"
    - name: Check links at reanimate.github.io
      run: |
        checklink --quiet --broken "https://reanimate.github.io/" > failures.txt
        if [ -s failures.txt ]; then
          cat failures.txt
          exit 1
        fi
